version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3001:3000
    depends_on:
      - db
