services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
