name: Build release Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: cps-backend
  DOCKER_REGISTRY_URL: ghcr.io

jobs:
  build_docker_images:
    # Job name that shows in the GitHub UI
    name: Build Docker Images
    # Runner to use
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE_NAME:latest

      - name: Create a latest image as well
        run: docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: $DOCKER_REGISTRY_URL
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push the latest tag
        run: docker push $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest

      - name: Remove the Docker image with latest tag
        run: docker rmi $DOCKER_REGISTRY_URL/$DOCKER_IMAGE_NAME:latest
